### PR TITLE
Move Directories to Poker, and avoid use of Rand

### PR DESCRIPTION
**Pull request by smarr**
I'd like to propose a few localized changes:

- remove env from Poker, since it is not used
- move the dictionary creation from ChatApp to Poker since only the poker really uses it, and it makes it easier in actor languages which do not allow sending around structured data as easily
- avoid the use of Pony's Rand class by having a copy of the shuffle method in the SimpleRand class

Happy to discuss/improve the changes.

### CODE REVIEW

**Comment by smarr** [comment]
The last commit also addresses https://github.com/sblessing/chat-app/issues/5

**Comment by sblessing** [comment]
Thank you.

Would it be possible to have a seperate PR for https://github.com/sblessing/chat-app/pull/3/commits/47568686fa11eb30dc26c6144365fda6a8fca79e?

I do agree with the refactorings except the local copy of shuffle, since we are still using the Random interface (from the package) and any local pony installation will have rand available. If we were to do that, we should remove the dependency to rand entirely.

**Comment by smarr** [comment]
The latest push drops the change on the separate PR (#6), and also drops the use of Pony's random package.

**Comment by sblessing** [comment]
Thanks!

**Pull request merged**
